import type {
  CronogramaCategory,
  CronogramaEvent,
  CronogramaPriority,
  CronogramaStatus,
} from './types';
import { CRONOGRAMA_CYCLE_YEARS } from '@/lib/cronograma-cycle';

export const CRONOGRAMA_YEARS = CRONOGRAMA_CYCLE_YEARS;

export const categoryLabels: Record<CronogramaCategory, string> = {
  governanca: 'Governança',
  programacao: 'Programação',
  infraestrutura: 'Infraestrutura',
  logistica: 'Logística',
  comunicacao: 'Comunicação',
  comercial: 'Comercial',
  cerimonial: 'Cerimonial',
};

export const statusLabels: Record<CronogramaStatus, string> = {
  confirmed: 'Confirmado',
  planned: 'Planejado',
  in_progress: 'Em andamento',
  completed: 'Concluído',
  overdue: 'Atrasado',
  rescheduled: 'Reprogramado',
  cancelled: 'Cancelado',
  undated: 'Sem data',
  in_definition: 'Em definição',
  blocked: 'Dependência',
};

export const priorityLabels: Record<CronogramaPriority, string> = {
  critical: 'Crítica',
  high: 'Alta',
  medium: 'Média',
  low: 'Baixa',
};

export const categoryTone: Record<CronogramaCategory, string> = {
  governanca: 'bg-emerald-700',
  programacao: 'bg-gold',
  infraestrutura: 'bg-slate-600',
  logistica: 'bg-primary',
  comunicacao: 'bg-sky-700',
  comercial: 'bg-amber-700',
  cerimonial: 'bg-rose-700',
};

export const officialCronogramaEvents: CronogramaEvent[] = [
  {
    id: 'gov-2026-08-comite',
    title: 'Instalação do comitê executivo 2028',
    summary: 'Alinhamento de governança, calendário macro e ritos de decisão para o ciclo 2026-2028.',
    date: '2026-08-18',
    startTime: '09:00',
    endTime: '11:00',
    year: 2026,
    category: 'governanca',
    status: 'confirmed',
    priority: 'high',
    kind: 'milestone',
    location: 'Sede da Fenasoja',
    owner: 'Presidência',
    commission: 'Comitê Central',
    isOfficial: true,
  },
  {
    id: 'meet-2026-09-central',
    title: 'Reunião central de integração das comissões',
    summary: 'Primeiro bloco de integração entre comissões, dependências e calendário compartilhado.',
    date: '2026-09-15',
    startTime: '18:30',
    endTime: '20:00',
    year: 2026,
    category: 'governanca',
    status: 'planned',
    priority: 'medium',
    kind: 'meeting',
    location: 'Auditório administrativo',
    owner: 'Secretaria Executiva',
    commission: 'Comitê Central',
    isCentralMeeting: true,
  },
  {
    id: 'infra-2026-11-masterplan',
    title: 'Entrega do masterplan preliminar do parque',
    summary: 'Consolidação de acessos, áreas técnicas, palcos, expositores e fluxos de visitantes.',
    date: '2026-11-24',
    startTime: '14:00',
    endTime: '17:00',
    year: 2026,
    category: 'infraestrutura',
    status: 'planned',
    priority: 'high',
    kind: 'deadline',
    location: 'Parque de Exposições',
    owner: 'Infraestrutura',
    commission: 'Infraestrutura',
    isOfficial: true,
  },
  {
    id: 'com-2026-12-narrativa',
    title: 'Definição da narrativa institucional 2028',
    summary: 'Territórios de mensagem, tom visual e linhas de campanha para a apresentação pública.',
    date: '2026-12-08',
    startTime: '10:00',
    endTime: '12:00',
    year: 2026,
    category: 'comunicacao',
    status: 'in_definition',
    priority: 'medium',
    kind: 'decision',
    owner: 'Comunicação',
    commission: 'Comunicação',
  },
  {
    id: 'meet-2027-02-central',
    title: 'Reunião central de abertura do ciclo 2027',
    summary: 'Revisão de entregas de 2026 e priorização do primeiro semestre de 2027.',
    date: '2027-02-09',
    startTime: '18:30',
    endTime: '20:15',
    year: 2027,
    category: 'governanca',
    status: 'confirmed',
    priority: 'medium',
    kind: 'meeting',
    location: 'Sede da Fenasoja',
    owner: 'Coordenação Geral',
    commission: 'Comitê Central',
    isCentralMeeting: true,
  },
  {
    id: 'comercial-2027-03-cotas',
    title: 'Lançamento do plano comercial de cotas',
    summary: 'Modelo de patrocínio, contrapartidas, prioridades comerciais e calendário de prospecção.',
    date: '2027-03-16',
    startTime: '09:30',
    endTime: '11:30',
    year: 2027,
    category: 'comercial',
    status: 'planned',
    priority: 'high',
    kind: 'milestone',
    location: 'Sala comercial',
    owner: 'Comissão Comercial',
    commission: 'Comercial',
    isOfficial: true,
  },
  {
    id: 'programacao-2027-05-curadoria',
    title: 'Curadoria preliminar de atrações e experiências',
    summary: 'Mapa de palcos, atrações técnicas, agenda cultural e experiências institucionais.',
    date: '2027-05-20',
    startTime: '14:00',
    endTime: '16:30',
    year: 2027,
    category: 'programacao',
    status: 'in_definition',
    priority: 'medium',
    kind: 'event',
    owner: 'Programação',
    commission: 'Programação',
    subevents: [
      { title: 'Mapa de palcos', status: 'planned', owner: 'Programação' },
      { title: 'Agenda técnica', status: 'in_definition', owner: 'Agronegócio' },
    ],
  },
  {
    id: 'log-2027-07-mobilidade',
    title: 'Desenho de mobilidade e acessos do parque',
    summary: 'Fluxo de veículos, bolsões de estacionamento, credenciais, transporte interno e contingências.',
    date: '2027-07-13',
    startTime: '08:30',
    endTime: '11:30',
    year: 2027,
    category: 'logistica',
    status: 'planned',
    priority: 'critical',
    kind: 'deadline',
    location: 'Parque de Exposições',
    owner: 'Comissão de Logística',
    commission: 'Logística',
    isOfficial: true,
  },
  {
    id: 'meet-2027-09-central',
    title: 'Reunião central de consolidação operacional',
    summary: 'Integração de infraestrutura, logística, comunicação, programação e comercial.',
    date: '2027-09-21',
    startTime: '18:30',
    endTime: '20:15',
    year: 2027,
    category: 'governanca',
    status: 'planned',
    priority: 'high',
    kind: 'meeting',
    location: 'Auditório administrativo',
    owner: 'Coordenação Geral',
    commission: 'Comitê Central',
    isCentralMeeting: true,
  },
  {
    id: 'cerimonial-2027-11-protocolo',
    title: 'Protocolo institucional e agenda de autoridades',
    summary: 'Fluxo de convites, recepção, composição de palco e agenda de relacionamento.',
    date: '2027-11-09',
    startTime: '15:00',
    endTime: '17:00',
    year: 2027,
    category: 'cerimonial',
    status: 'planned',
    priority: 'medium',
    kind: 'decision',
    owner: 'Cerimonial',
    commission: 'Cerimonial',
  },
  {
    id: 'gov-2028-01-retomada',
    title: 'Retomada executiva da reta final',
    summary: 'Revisão de riscos, responsáveis, entregas críticas e cadência semanal até a feira.',
    date: '2028-01-18',
    startTime: '08:30',
    endTime: '10:30',
    year: 2028,
    category: 'governanca',
    status: 'confirmed',
    priority: 'critical',
    kind: 'milestone',
    location: 'Sede da Fenasoja',
    owner: 'Presidência',
    commission: 'Comitê Central',
    isOfficial: true,
    isMain: true,
  },
  {
    id: 'meet-2028-02-central',
    title: 'Reunião central da reta final',
    summary: 'Conferência de pendências críticas, comunicação de prazos e alinhamento de operação.',
    date: '2028-02-15',
    startTime: '18:30',
    endTime: '20:30',
    year: 2028,
    category: 'governanca',
    status: 'confirmed',
    priority: 'critical',
    kind: 'meeting',
    location: 'Sede da Fenasoja',
    owner: 'Coordenação Geral',
    commission: 'Comitê Central',
    isCentralMeeting: true,
    isMain: true,
  },
  {
    id: 'infra-2028-03-vistoria',
    title: 'Vistoria técnica final do parque',
    summary: 'Checagem de montagem, energia, segurança, circulação, sinalização e áreas sensíveis.',
    date: '2028-03-22',
    startTime: '08:00',
    endTime: '12:00',
    year: 2028,
    category: 'infraestrutura',
    status: 'planned',
    priority: 'critical',
    kind: 'deadline',
    location: 'Parque de Exposições',
    owner: 'Infraestrutura',
    commission: 'Infraestrutura',
    isOfficial: true,
  },
  {
    id: 'com-2028-04-campanha',
    title: 'Entrada da campanha institucional final',
    summary: 'Virada de comunicação, mídia, releases, peças finais e régua de divulgação diária.',
    date: '2028-04-03',
    startTime: '09:00',
    endTime: '10:30',
    year: 2028,
    category: 'comunicacao',
    status: 'planned',
    priority: 'high',
    kind: 'milestone',
    owner: 'Comunicação',
    commission: 'Comunicação',
    isOfficial: true,
  },
  {
    id: 'log-2028-04-simulacao',
    title: 'Simulação operacional de logística',
    summary: 'Teste de acesso, credenciamento, transporte interno, fornecedores, emergências e comunicação de campo.',
    date: '2028-04-14',
    startTime: '07:30',
    endTime: '11:30',
    year: 2028,
    category: 'logistica',
    status: 'planned',
    priority: 'critical',
    kind: 'event',
    location: 'Parque de Exposições',
    owner: 'Comissão de Logística',
    commission: 'Logística',
    isMain: true,
    subevents: [
      { title: 'Acessos e estacionamento', date: '2028-04-14', owner: 'Logística', status: 'planned' },
      { title: 'Transporte interno', date: '2028-04-14', owner: 'Logística', status: 'planned' },
      { title: 'Contingência de clima', date: '2028-04-14', owner: 'Operação', status: 'in_definition' },
    ],
  },
  {
    id: 'cerimonial-2028-04-abertura',
    title: 'Ensaio de abertura oficial',
    summary: 'Roteiro, palco, autoridades, recepção e fluxo de imprensa para a cerimônia de abertura.',
    date: '2028-04-27',
    startTime: '15:00',
    endTime: '17:30',
    year: 2028,
    category: 'cerimonial',
    status: 'in_definition',
    priority: 'critical',
    kind: 'event',
    location: 'Palco institucional',
    owner: 'Cerimonial',
    commission: 'Cerimonial',
    isMain: true,
  },
  {
    id: 'fenasoja-2028-abertura',
    title: 'Abertura oficial Fenasoja 2028',
    summary: 'Marco principal da feira, com recepção institucional e ativação completa das áreas operacionais.',
    date: '2028-05-01',
    startTime: '10:00',
    endTime: '12:00',
    year: 2028,
    category: 'cerimonial',
    status: 'confirmed',
    priority: 'critical',
    kind: 'event',
    location: 'Parque de Exposições',
    owner: 'Presidência',
    commission: 'Comitê Central',
    isMain: true,
    isOfficial: true,
  },
  {
    id: 'fenasoja-2028-operacao',
    title: 'Operação oficial da Fenasoja 2028',
    summary: 'Período oficial de feira, com acompanhamento diário de programação, logística e comunicação.',
    date: '2028-05-02',
    startTime: '08:00',
    endTime: '22:00',
    year: 2028,
    category: 'programacao',
    status: 'confirmed',
    priority: 'critical',
    kind: 'event',
    location: 'Parque de Exposições',
    owner: 'Coordenação Geral',
    commission: 'Comitê Central',
    isMain: true,
    isOfficial: true,
    subevents: [
      { title: 'Agenda cultural', date: '2028-05-02', owner: 'Programação', status: 'planned' },
      { title: 'Operação de visitantes', date: '2028-05-02', owner: 'Logística', status: 'planned' },
    ],
  },
  {
    id: 'fenasoja-2028-encerramento',
    title: 'Encerramento e balanço preliminar',
    summary: 'Fechamento institucional, coleta de indicadores e primeiras lições operacionais.',
    date: '2028-05-10',
    startTime: '18:00',
    endTime: '20:00',
    year: 2028,
    category: 'governanca',
    status: 'planned',
    priority: 'high',
    kind: 'milestone',
    location: 'Parque de Exposições',
    owner: 'Coordenação Geral',
    commission: 'Comitê Central',
    isOfficial: true,
  },
  {
    id: 'pend-programacao-grade-final',
    title: 'Fechamento da grade de atrações externas',
    summary: 'A grade depende de confirmação contratual e janela de disponibilidade de fornecedores.',
    date: null,
    year: 2028,
    category: 'programacao',
    status: 'in_definition',
    priority: 'high',
    kind: 'decision',
    owner: 'Programação',
    commission: 'Programação',
    pendingReason: 'Contrato e disponibilidade ainda sem data oficial.',
    decisionNeeded: 'Definir data limite de confirmação e plano alternativo.',
  },
  {
    id: 'pend-comercial-patrocinio-master',
    title: 'Cota master em negociação',
    summary: 'A proposta comercial precisa de aprovação final para encaixe de mídia e ativações.',
    date: null,
    year: 2027,
    category: 'comercial',
    status: 'in_definition',
    priority: 'medium',
    kind: 'decision',
    owner: 'Comercial',
    commission: 'Comercial',
    pendingReason: 'Negociação em aberto com impacto na comunicação.',
    decisionNeeded: 'Confirmar contrapartidas e prazo de assinatura.',
  },
  {
    id: 'pend-infra-alvara',
    title: 'Janela de liberação técnica e alvarás',
    summary: 'Dependência de documentação, vistoria e validação externa antes do início da montagem.',
    date: null,
    year: 2028,
    category: 'infraestrutura',
    status: 'blocked',
    priority: 'critical',
    kind: 'decision',
    owner: 'Infraestrutura',
    commission: 'Infraestrutura',
    pendingReason: 'Aguardando agenda de validação externa.',
    decisionNeeded: 'Formalizar responsável e prazo de retorno.',
  },
  {
    id: 'pend-logistica-credenciais',
    title: 'Critérios finais de credenciais operacionais',
    summary: 'Regra de acesso para fornecedores, equipe de campo e veículos de apoio ainda precisa de data de corte.',
    date: null,
    year: 2028,
    category: 'logistica',
    status: 'in_definition',
    priority: 'high',
    kind: 'decision',
    owner: 'Comissão de Logística',
    commission: 'Logística',
    pendingReason: 'Dependência de fornecedores e desenho final de acessos.',
    decisionNeeded: 'Definir data de corte e matriz de aprovação.',
  },
];
