
-- 1) New columns to track who actually started GPS for each transport
ALTER TABLE public.transports
  ADD COLUMN IF NOT EXISTS tracking_started_by_user_id uuid,
  ADD COLUMN IF NOT EXISTS tracking_started_at timestamptz;

-- 2) Updated RPC: prefer the user who started tracking; if empty, claim it.
CREATE OR REPLACE FUNCTION public.publish_transport_location(
  _transport_id uuid,
  _latitude double precision,
  _longitude double precision,
  _accuracy double precision DEFAULT NULL,
  _speed double precision DEFAULT NULL,
  _heading double precision DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_transport public.transports%ROWTYPE;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Não autenticado';
  END IF;

  SELECT * INTO v_transport FROM public.transports WHERE id = _transport_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transporte não encontrado';
  END IF;

  IF NOT public.is_org_member(v_user, v_transport.org_id) THEN
    RAISE EXCEPTION 'Sem acesso ao transporte';
  END IF;

  IF v_transport.status NOT IN ('em_andamento','em_retorno','chegou_destino') THEN
    RAISE EXCEPTION 'Transporte não está ativo';
  END IF;

  -- Claim ownership of GPS publishing if no one owns it yet
  IF v_transport.tracking_started_by_user_id IS NULL THEN
    UPDATE public.transports
       SET tracking_started_by_user_id = v_user,
           tracking_started_at = now()
     WHERE id = _transport_id
       AND tracking_started_by_user_id IS NULL;
    v_transport.tracking_started_by_user_id := v_user;
  END IF;

  -- Only the GPS owner publishes
  IF v_transport.tracking_started_by_user_id <> v_user THEN
    RAISE EXCEPTION 'Outro usuário já está publicando a localização desta viagem';
  END IF;

  INSERT INTO public.transport_locations (
    transport_id, org_id, driver_user_id,
    latitude, longitude, accuracy, speed, heading, updated_at
  ) VALUES (
    _transport_id, v_transport.org_id, v_user,
    _latitude, _longitude, _accuracy, _speed, _heading, now()
  )
  ON CONFLICT (transport_id) DO UPDATE
    SET driver_user_id = EXCLUDED.driver_user_id,
        latitude = EXCLUDED.latitude,
        longitude = EXCLUDED.longitude,
        accuracy = EXCLUDED.accuracy,
        speed = EXCLUDED.speed,
        heading = EXCLUDED.heading,
        updated_at = now();
END;
$$;

-- 3) Purge stale live-location rows of inactive transports
DELETE FROM public.transport_locations tl
USING public.transports t
WHERE tl.transport_id = t.id
  AND t.status NOT IN ('em_andamento','em_retorno','chegou_destino');

-- 4) Backfill voo_cidade where it's missing but destino tells the airport
UPDATE public.transports
   SET voo_cidade = 'Santo Ângelo'
 WHERE titulo = 'Aeroporto'
   AND voo_cidade IS NULL
   AND lower(destino) LIKE '%santo%ângelo%';

UPDATE public.transports
   SET voo_cidade = 'Passo Fundo'
 WHERE titulo = 'Aeroporto'
   AND voo_cidade IS NULL
   AND lower(destino) LIKE '%passo%fundo%';

UPDATE public.transports
   SET voo_cidade = 'Chapecó'
 WHERE titulo = 'Aeroporto'
   AND voo_cidade IS NULL
   AND lower(destino) LIKE '%chapec%';

UPDATE public.transports
   SET voo_cidade = 'Porto Alegre'
 WHERE titulo = 'Aeroporto'
   AND voo_cidade IS NULL
   AND lower(destino) LIKE '%porto%alegre%';

-- 5) Canonical airport coordinates for Aeroporto trips (overwrite mismatches too)
UPDATE public.transports
   SET destino_lat = -27.1342, destino_lng = -52.6566
 WHERE titulo = 'Aeroporto' AND voo_cidade = 'Chapecó'
   AND status IN ('pendente','em_andamento','chegou_destino','em_retorno');

UPDATE public.transports
   SET destino_lat = -28.2434, destino_lng = -52.3261
 WHERE titulo = 'Aeroporto' AND voo_cidade = 'Passo Fundo'
   AND status IN ('pendente','em_andamento','chegou_destino','em_retorno');

UPDATE public.transports
   SET destino_lat = -28.2823, destino_lng = -54.1693
 WHERE titulo = 'Aeroporto' AND voo_cidade = 'Santo Ângelo'
   AND status IN ('pendente','em_andamento','chegou_destino','em_retorno');

UPDATE public.transports
   SET destino_lat = -29.9939, destino_lng = -51.1714
 WHERE titulo = 'Aeroporto' AND voo_cidade = 'Porto Alegre'
   AND status IN ('pendente','em_andamento','chegou_destino','em_retorno');

-- 6) Drop suspicious tiny polylines so they get regenerated by the Maps API
UPDATE public.transports
   SET rota_polyline = NULL,
       duracao_estimada_min = NULL,
       distancia_estimada_km = NULL
 WHERE rota_polyline IS NOT NULL
   AND length(rota_polyline) < 200
   AND status IN ('pendente','em_andamento','chegou_destino','em_retorno');
